### ISSUE TITLE
Provide PEP 484 compatible type annotations

### ISSUE THREAD

**Issue by RoGryza** [hetznercloud/hcloud-python#105]
## Feature Request

~I'd like to type check code using this lib with mypy, but it doesn't type check sphinx type directives in docstrings. [Stub files](https://www.python.org/dev/peps/pep-0484/#stub-files) could provide type hints without having to change the current code, I'd be willing to submit a PR if that's desirable.~

EDIT: Sorry, I looked into the code and it's already annotated. It seems like a `hcloud/py.typed` file is needed though, according to the [mypy docs](https://mypy.readthedocs.io/en/latest/installed_packages.html?highlight=py.typed#making-pep-561-compatible-packages). I set up a local clone with a py.typed file and mypy can import hcloud now, though it still doesn't typecheck, the following gives me no warnings for instance:

```py
foo: int = hcloud.Client(self.token).servers.get_by_name(234)
```

Also, it seems that some types are not set correcly:
```
hcloud-python/hcloud/certificates/client.py:81: error: Type signature has too few arguments
hcloud-python/hcloud/certificates/client.py:103: error: Type signature has too few arguments
hcloud-python/hcloud/floating_ips/client.py:41: error: Type signature has too few arguments
hcloud-python/hcloud/volumes/client.py:24: error: Type signature has too few arguments
hcloud-python/hcloud/volumes/client.py:40: error: Type signature has too few arguments
hcloud-python/hcloud/volumes/client.py:72: error: Type signature has too few arguments
hcloud-python/hcloud/volumes/client.py:236: error: Type signature has too few arguments
hcloud-python/hcloud/volumes/client.py:266: error: Type signature has too few arguments
hcloud-python/hcloud/images/client.py:51: error: Type signature has too few arguments
hcloud-python/hcloud/load_balancers/client.py:339: error: syntax error in type comment '(...) -> CreateLoadBalancerResponse:'
Found 10 errors in 5 files (checked 1 source file)
```

**Comment by LKaemmerling** [comment]
Hey @RoGryza,

thank you for your issue. We would accept such a PR, so if you want you can submit a PR, otherwise we would look into it when we find some time, as the issue is not "critical".

**Comment by RoGryza** [comment]
@LKaemmerling I got started in a fork ([here](https://github.com/RoGryza/hcloud-python)), though to typecheck the Bound* model attributes and PageResults I think a mypy plugin would be needed. Would such a plugin be welcome in a PR also? Else I'll work on a separate `hcloud-stubs` package.

**Comment by LKaemmerling** [comment]
I would prefer to take one step after the other :) We should keep in mind that we still support Py 2.7 so using `typing` might be a problem.

**Comment by RoGryza** [comment]
Well, that breaks my fork. Isn't there a backported typing package?
I'll try to submit a 2.7-compatible PR, if anything comes I'll comment here
