### ISSUE TITLE
New root password is not available after server rebuild

### ISSUE THREAD

**Issue by MarkusBauer** [hetznercloud/hcloud-python#108]
## Bug Report

**Current Behavior**
When rebuilding a server from an image, and this server _has no ssh key_ associated, a new root password is generated. 
According to the [API documentation](https://docs.hetzner.cloud/#server-actions-rebuild-a-server-from-an-image) this new password is returned in key `root_password` of the HTTP response. From the Python API, this new root password is not available, making rebuilt servers inaccessible. 

**Input Code**
Something along these lines might reproduce the issue:
```python
client = Client('<token>')
response = client.servers.create('testbox', ServerType(name='cx11'), Image(name='debian-10'))
print('root =', response.root_password)
time.sleep(60)
server = client.servers.get_by_name('testbox')
response = server.rebuild(Image(name='debian-10'))
print('root =', '???') # problem here - response is of type BoundAction not containing the password
```

**Expected behavior/code**
In [servers/client.py](https://github.com/hetznercloud/hcloud-python/blob/master/hcloud/servers/client.py#L696-L698), the root password trashed. It could for example be returned as second return argument, or added to the action's response, or be added to the server object. The wrapper method in [line 199](https://github.com/hetznercloud/hcloud-python/blob/master/hcloud/servers/client.py#L199) might also need adaption to return the new root password. 

**Environment**
- Python Version: 3.6
- Hcloud-Python Version: 1.10.0 (and current master branch)

**Comment by LKaemmerling** [comment]
I will look into how we can fix it in the new year, thank you!

**Comment by LKaemmerling** [comment]
I think there is no easy way to fix this without breaking change. In your use case, I would suggest requesting a new root password instead (function reset_password).
