### ISSUE TITLE
Package `hcloud` for conda (forge)

### ISSUE THREAD

**Issue by s-m-e** [hetznercloud/hcloud-python#113]
## Feature Request

In `conda`-based Python deployments (common in science etc.), it would be rather useful to have `hcloud` available as a conda / [conda-forge](https://conda-forge.org/) package.

Technically, `pip` is also available in `conda`-based environments and sort of integrates with `conda`, but using it can cause non-deterministic behavior down the line. Using `pip` should therefore be avoided in this context if possible.

Because `hcloud` does not contain non-Python components as far as I can see, the packaging process should be trivial. Guidelines can be found [here](https://conda-forge.org/#add_recipe). If any help is required, I have done this before ;)

**Comment by smoe** [comment]
And I would happily sponsor a package for Debian.

**Comment by s-m-e** [comment]
Ping (counteracting the stale-bot).

**Comment by s-m-e** [comment]
I can not remove the `state` flag, but the issue persists. Please re-open.

**Comment by LKaemmerling** [comment]
Hey @s-m-e,

sorry, the stale bot has a bit bad settings. I will correct this.

For the Issue:

Currently, we don't plan to publish the hcloud-python somewhere else than on pip (ourselves). We know about (community packaged) packages for Alpine Linux and many others, maybe this would fit here too?

**Comment by s-m-e** [comment]
@LKaemmerling 

I would indeed be a fit. The question then becomes what your policy is (if there is any at all) with respect packaging by the community.

If you do not mind, I'd move ahead and package this for conda forge. Because I do not "own" this package, the conda forge people would expect some sort of a "green light" from you. A reply here on Github that I can link to should be sufficient.

**Comment by s-m-e** [comment]
Ping.

**Comment by s-m-e** [comment]
Hi @LKaemmerling - after having waited for a while, I am pushing this a little ;) I have [started the process of getting hcloud-python into conda-forge](https://github.com/conda-forge/staged-recipes/pull/17811). I have been working on a package built on top of `hcloud` that is designed specifically to run on top of conda packages, [HPC clusers via Dask for the Hetzner cloud](https://scherbelberg.readthedocs.io/), that I can not release as-is without `hcloud` present in this ecosystem.

Please object if you do not want this to move forward. If you agree to have a package there, we should sort out a direct communication path so I can update the conda-forge package in a timely manner whenever you push a new potentially security-critical release to pypi. If you want to maintain the conda-forge package yourself after all, it's a single-text-file-change plus Github-PR-kind-of-workflow, I am more than happy to hand the maintainer-role over.
