### ISSUE TITLE
Lack of persistent HTTP connections for API requests, high HTTPS connection overhead

### ISSUE THREAD

**Issue by SpComb** [hetznercloud/hcloud-python#114]
## Feature Request

The `hcloud.Client` should use a [requests Session object](https://requests.readthedocs.io/en/latest/user/advanced/#session-objects) for persistent HTTPS connections, avoiding a great deal of HTTPS connection latency/overhead when performing many API requests.

Using a rough `time ...` comparison, this change alone seems to reduce the runtime for an Ansible dynamic inventory script making lots of hetzner cloud API requests from ~32s -> ~18s.

**Is your feature request related to a problem? Please describe.**

Using `logging.getLogger("urllib3").setLevel(logging.DEBUG)` to show the individual API requests the library is making, I noticed that requests is establishing a new HTTPS connection for each API request:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hetzner.cloud:443
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/servers?label_selector=...&page=1&per_page=50 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hetzner.cloud:443
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/networks/... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hetzner.cloud:443
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/networks/... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hetzner.cloud:443
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/volumes/... HTTP/1.1" 200 None
```

**Describe the solution you'd like**

Changing the [`Client.request`](https://github.com/hetznercloud/hcloud-python/blob/v1.11.0/hcloud/hcloud.py#L198-L203) method to use a [`requests.Session`](https://requests.readthedocs.io/en/latest/api/#requests.Session) avoids the HTTPS connection overhead:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.hetzner.cloud:443
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/servers?label_selector=...&page=1&per_page=50 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/networks/... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/networks/... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.hetzner.cloud:443 "GET /v1/volumes/... HTTP/1.1" 200 None
```

**Describe alternatives you've considered**
None

**Teachability, Documentation, Adoption, Migration Strategy**
This should be a completely transparent performance improvement for all users using a `hcloud.Client(...)` instance.

**Comment by SpComb** [comment]
FWIW I optimized our dynamic inventory plugin to only do a single `client.networks.get_all()` call, instead of reloading the same network for each `client.servers.get_all()` -> `server.private_net` -> `n.network`... with just four list requests, the HTTPS connection overhead isn't noticeable anymore, but it sure is for the tens of individual `BoundModelBase.reload()` API requests we were doing before.

**Comment by LKaemmerling** [comment]
Hey @SpComb,

this sounds like a good idea for me. Would you like to submit a PR that improves this?

> FWIW I optimized our dynamic inventory plugin to only do a single `client.networks.get_all()` call, instead of reloading the same network for each `client.servers.get_all()` -> `server.private_net` -> `n.network`... with just a couple of list API requests, the HTTPS connection overhead isn't noticeable anymore, but it sure is for the tens of individual `BoundModelBase.reload()` API requests we were doing before.

@SpComb that sounds interesting! Can you think of contributing it to the upstream? (https://github.com/ansible-collections/hetzner.hcloud)

**Comment by SpComb** [comment]
> this sounds like a good idea for me. Would you like to submit a PR that improves this?

Yes, I tested this with a monkey-patch to the class, it should be a neat enough PR.

> @SpComb that sounds interesting! Can you think of contributing it to the upstream? (https://github.com/ansible-collections/hetzner.hcloud)

This is for a custom dynamic inventory plugin that provides additional information about the attached private networks, volumes and floating IPs... based on a quick look at the upstream plugin, I think it only does a single GET for an explicitly configured `network`, so the same optimization doesn't really apply.

We use the dynamic inventory vars to configure systemd-networkd networks and LVM PVs.
