### ISSUE TITLE
firewalls.apply_to_resources makes no sense

### ISSUE THREAD

**Issue by uroflavin** [hetznercloud/hcloud-python#115]
## Bug Report

**Current Behavior**
I'm not able to assign my server ressource with this kind of implementation.
Either the documentation does not fit or the implementation or both

**Input Code**
```python
    def apply_to_resources(self, firewall, resources):
        # type: (Firewall, List[FirewallResource]) -> List[BoundAction]
        """Applies one Firewall to multiple resources.

        :param firewall: :class:`BoundFirewall <hcloud.firewalls.client.BoundFirewall>` or  :class:`Firewall <hcloud.firewalls.domain.Firewall>`
        :param rules: List[:class:`FirewallResource <hcloud.firewalls.domain.FirewallResource>`]
        :return: List[:class:`BoundAction <hcloud.actions.client.BoundAction>`]
        """
        data = {
            "apply_to": []
        }
        for resource in resources:
            data['apply_to'].append(resource.to_payload())
        response = self._client.request(
            url="/firewalls/{firewall_id}/actions/apply_to_resources".format(firewall_id=firewall.id),
            method="POST", json=data)
        return [BoundAction(self._client.actions, _) for _ in response['actions']]
```

**Expected behavior/code**
I like to assign the server-ressource to the firewall.

**Environment**
- Python Version: doesn't matter
- Hcloud-Python Version: current

**Possible Solution**

**Comment by uroflavin** [comment]
Code-Snipped is from https://hcloud-python.readthedocs.io/en/latest/_modules/hcloud/firewalls/client.html#FirewallsClient.apply_to_resources

**Comment by LKaemmerling** [comment]
Hey @uroflavin,

sorry for the late answer!

Basically, you need to use a `FirewallResource`  (`hcloud.firewalls.domain.FirewallResource`) (as stated in the documentation), not a `Server`.  The FirewallResource is a Wrapper around a Server (currently the only supported resource, but there might be more in the future).

Does this help you @uroflavin?
- Lukas

**Comment by uroflavin** [comment]
Sorry, my fault. I should be more precisely.

the documentation name it „rules“, the function named it „resources“ - and now you introduce me to assign a firewall Ressource (which is a server) - to what? a Firewall-ressource ...

my main concern was the documentation, now with your explanation I’m just more confused than before... 

My intention was, to get the doc-string fixed.  🙃

**Comment by LKaemmerling** [comment]
Hey @uroflavin,

thank you, I submitted an MR to fix the docstring.

Basically, it is quite easy to use, you can find a sample within out tests: https://github.com/hetznercloud/hcloud-python/blob/master/tests/unit/firewalls/test_client.py#L307 (or for the BoundFirewall: https://github.com/hetznercloud/hcloud-python/blob/master/tests/unit/firewalls/test_client.py#L133)

**Comment by uroflavin** [comment]
great work - thank you!
