### ISSUE TITLE
Don't force me to reset root password after creating a server

### ISSUE THREAD

**Issue by codethief** [hetznercloud/hcloud-python#121]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'm spinning up and delegating workloads to servers in an automated fashion using hcloud-python. Since this is a fully automated setup, I don't want to deal with configuring SSH keys because, if everything goes as planned, I'll only ever connect to a given server once. Hence, I simply wanted to use the root password the API returns in its CreateServerResponse. However, once I connect via SSH I'm forced to reset the password – which I find completely unnecessary and which severely hinders automation because Python libraries like Paramiko, AsyncSSH, Plumbum, Fabric, etc. are not prepared for that.

**Describe the solution you'd like**

Provide an option for `ServersClient.create()` to disable the reset-password policy.

**Describe alternatives you've considered**

- I suppose there might be a way to disable the policy using cloud-init but I haven't figured that out yet.
- Generate an SSH key using some Python library, register it with the Hetzner Cloud API, invoke `ServersClient.create()` with that key, use server, tear down server, delete SSH key from project. Unfortunately, this adds an additional stack of dependencies just for generating a key which I want to use *once*.

PS: I realize that this request concerns the Cloud API much more than it concerns hcloud-python. However, I didn't know where else to post this and, as outlined above, I also think this is much more of an obstacle for full automation (in Python) than it is for, say, casual users of the Cloud CLI.

**Comment by codethief** [comment]
UPDATE: I indeed found a workaround using cloud-init which doesn't even require me to set the password myself:

```
#cloud-config
chpasswd:
  # Don't force us to reset root password when we log in for the first time
  expire: False
```

That's much simpler than I expected, so I'm gonna close this issue.

**Comment by LKaemmerling** [comment]
Hey @codethief,

actually, this is a security measurement. We send the root password as plain text to your e-mail address (when you don't use SSH Keys), so there is theoretically the possibility that an attacker could get your password. 

We always recommend using SSH Keys for such automated setups. As a sample with ansible (or terraform) you can easily generate ssh keys for a single server (& then spin up the server).

I will close the issue as you found a workaround and asked to close the issue.
Have a nice day!
- Lukas

**Comment by LKaemmerling** [comment]
> Hi Lukas, thanks so much for your response!
> 
> > We send the root password as plain text to your e-mail address
> 
> Good point. Is there a way to prevent that?

Yep, use SSH Keys :) Then the root password won't be sent to you.

**Comment by codethief** [comment]
The reason I was trying to prevent SSH keys is that 

- they require separate registering/unregistering in Hetzner Cloud, increasing the complexity when I want to set up multiple servers on the fly. (From the POV of my application they're effectively global state and I have to avoid name collisions and so on and so forth.)
- dealing with SSH keys in Python is extremely cumbersome and some SSH libraries even require you to mess with the files in `~/.ssh/` (or at least force you to write your key to permanent storage which I don't want to do).

The thing with a root password is: If you didn't send it to me via email (i.e. announce it publicly), it'd actually be just as safe as an SSH key for the root user account. (Provided, of course, it's long enough but that can be arranged for.)
