### ISSUE TITLE
hcloud-python]$ make docs fails sphinx 4.x

### ISSUE THREAD

**Issue by doczkal** [hetznercloud/hcloud-python#126]
## Bug Report

**Current Behavior**
'make docs' fails with sphinx 4.0.2 (latest release). app.add_javascript() is removed.
'make docs' outputs a warning that app.add_javascript() is deprecated.

**Input Code**
Running Sphinx **v3.5.4**
making output directory... done
/home/tdoczkal/git/hcloud-python/docs/conf.py:166: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript('js/open_links_in_new_tab.js')

```python
hcloud-python]$ make docs
```

**Expected behavior/code**
build docs

**Environment**
- Python Version: v3.8.8
- Hcloud-Python Version: v.1.12.0 (latest release)

**Comment by LKaemmerling** [comment]
Hey @doczkal,

thank you for the report! I have fixed the issues in the MR https://github.com/hetznercloud/hcloud-python/pull/128.

**Comment by asarubbo** [comment]
Hi, I would like to ask if is possible to make a new release since we got a Gentoo downstream report about this issue. Thanks
