### ISSUE TITLE
Consider moving to docstings for documenting API

### ISSUE THREAD

**Issue by LD250** [hetznercloud/hcloud-python#13]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I (as a library user) have an issue referring to the "readthedocs" every time I need to understand how I should use a method

I (as a library developer) have a problem with maintaining docs. I would be much easier for me to document my code inside a docstring.

**Describe the solution you'd like**
I would like to use a docstrings for documenting methods/objects and then run `sphinx-apidoc` to create documentation for me

**Describe alternatives you've considered**
The alternative is what we have right now. We document everything directly in *.rst files

**Teachability, Documentation, Adoption, Migration Strategy**
I would like to adopt `requests` library approach. They have a custom table of content, but they refer to autogenerated code inside documentation.
Example: https://github.com/kennethreitz/requests/blob/master/docs/api.rst

**Comment by LKaemmerling** [comment]
Done with 5c82152
