### ISSUE TITLE
`FirewallsClient.create` never returns `action`

### ISSUE THREAD

**Issue by felixscheinost** [hetznercloud/hcloud-python#131]
## Bug Report

**Current Behavior**

`FirewallsClient.create` looks for key `action` in the response while the actual key should be `actions` (notice the trailing `s`).

[Python `action`](https://github.com/hetznercloud/hcloud-python/blob/2b1c72e60bbddae19d677785d6c6beedcb943184/hcloud/firewalls/client.py#L267)

[Go `actions`](https://github.com/hetznercloud/hcloud-go/blob/4cf75f4cdc3e6885eaf0bd4316fa544eba0cf00d/hcloud/firewall.go#L258)

[REST documentation `actions`](https://docs.hetzner.cloud/#firewalls-create-a-firewall)

**Comment by LKaemmerling** [comment]
Thank you! I fixed it wiht #134

**Comment by felixscheinost** [comment]
Cool! Thanks! 😃
