### ISSUE TITLE
`FirewallRequest.create` add argument `apply_to`

### ISSUE THREAD

**Issue by felixscheinost** [hetznercloud/hcloud-python#132]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The [REST documentation](https://docs.hetzner.cloud/#firewalls-create-a-firewall) and the [Go client](https://github.com/hetznercloud/hcloud-go/blob/4cf75f4cdc3e6885eaf0bd4316fa544eba0cf00d/hcloud/firewall.go#L219) both support an argument to immediately apply a new firewall to a server on creation.

The Python client should do so as well.

**Comment by LKaemmerling** [comment]
Thank you! This was fixed with #134

**Comment by felixscheinost** [comment]
Awesome! Thank you!
