### ISSUE TITLE
update_service doesn't recognize changed certificates

### ISSUE THREAD

**Issue by dithmer** [hetznercloud/hcloud-python#133]
## Bug Report

**Current Behavior**
Hi!

We are facing an issue with the update_service method for loadbalancers. We are trying to add/delete certificates within the http-Object of a service. After adding or deleting a certificate inside the http-Object and calling the update_service method, the changes aren't made.

**Input Code**
Example:

```python
created_cert = hcloud_client.certificates.create(
    name=f"{cert_name}_{datetime.strftime(datetime.now(), '%Y%m%d')}",
    certificate=cert["fullchain"],
    private_key=decrypted_privkey.decode('utf-8'),
)

hcloud_load_balancers = hcloud_client.load_balancers.get_all()

for load_balancer in hcloud_load_balancers:
    for service in load_balancer.services:
      service.http.certificates.append(created_cert)
      update_service_action  = load_balancer.update_service(service)
      update_service_action.wait_until_finished()
```

We already debugged the code, and especially looked into the `service.http.certificates`-object/list, before calling update_service, to observe, if the certificate is inside the `service`-object. Everything seems fine. The `update_service_action.status` also contains `success` after calling it.

**Expected behavior/code**
We would think, the above code should add a new certificate to the specified loadbalancers service.
- Python Version: 3.8
- Hcloud-Python Version: 1.12.0

**Comment by LKaemmerling** [comment]
Hey @dithmer,

i tried it with your code above and for me it works perfectly, can you try it again?
