### ISSUE TITLE
Provide an enum of available datacenters server types etc.

### ISSUE THREAD

**Issue by firstdorsal** [hetznercloud/hcloud-python#148]
Hi, could you provide a list of the available datacenters and server ids for use in other applications.? I haven't found a good list of those resources.
like: 
- nbg1, ...
- cx11, ...

**Comment by tea-418** [comment]
Yes please.
The best method I found is creating an client of the Service, getting all and printing the name or id of each.
If you still need it my small work around below:
```python
from hcloud import Client
from hcloud.load_balancer_types.client import LoadBalancerTypesClient

client = Client(token="bmV2ZXIgZ29ubmEgZ2l2ZSB5b3UgdXAgbmV2ZXIgZ29ubmEgbGV0IHlvdSBkb3duDQo")
lbc = LoadBalancerTypesClient(client)

for lb in lbc.get_all():
    print(lb.name)
```

**Comment by gc-ss** [comment]
+1

I had a orthogonal requirement: https://github.com/hetznercloud/terraform-provider-hcloud/issues/520

**Comment by LKaemmerling** [comment]
Hello,

as @tea-418 already wrote, you can get all values easily through the API or through the CLI. As those recourses might change we won't add them as enums to the code.
