### ISSUE TITLE
Dependency resolution fails due to unnecessary upper bound

### ISSUE THREAD

**Issue by justinmayer** [hetznercloud/hcloud-python#155]
## Bug Report

**Current Behavior**

If you have a project that specifies Python in its pyproject.toml file like so:

```toml
[tool.poetry.dependencies]
python = ">=3.10,<4.0"
```

… and then try to add Hcloud-Python as a dependency:

```shell
poetry add hcloud
```

… dependency resolution will fail:

>   The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
>  - hcloud requires Python !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.11, so it will not be satisfied for Python >=3.11,<4.0
>
> Because hcloud (1.17.0) requires Python !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.11
> and no versions of hcloud match >1.17.0,<2.0.0, hcloud is forbidden.
> So, because fortressa depends on hcloud (^1.17.0), version solving failed.

**Expected behavior/code**

The expected behavior is that dependency resolution would not fail.

**Environment**
- Python Version: v3.10.5
- Hcloud-Python Version: v1.17.0
- Poetry 1.2.0b3

**Possible Solution**

The best way to address this problem is most likely to remove the upper bound from the [relevant line in `setup.py`](https://github.com/hetznercloud/hcloud-python/blob/fad870790a19621fd130fd28d564a8d6ba7a566c/setup.py#L37).

As was noted when the [Black project dropped upper bounds](https://github.com/psf/black/pull/2718):

> "[Upper bounds] mostly cause unnecessary trouble."

**Comment by justinmayer** [comment]
This issue is still present and relevant, which I have just confirmed on the latest Hcloud-Python v1.17.0 release. I have correspondingly updated the issue description to account for these details.

@LKaemmerling: Would you be so kind as to consider addressing this issue in the next Hcloud-Python release?

**Comment by LKaemmerling** [comment]
Hey @justinmayer,

will be fixed with the next release :)

**Comment by justinmayer** [comment]
Much appreciated, Lukas. I look forward to those enhancements landing in a published release soon. ✨

**Comment by justinmayer** [comment]
I confirmed that v1.18.0 addresses this issue. Once again, thank you for the prompt attention. 👏
