### ISSUE TITLE
Changelog doesn't contain 1.17.0 release notes

### ISSUE THREAD

**Issue by jcgruenhage** [hetznercloud/hcloud-python#161]

**Comment by LKaemmerling** [comment]
Hey @jcgruenhage,

with the last release we moved to publish the changelog in Github Releases. Therefore it is "expected".

**Comment by jcgruenhage** [comment]
It might be intentional, but as a user it's certainly not expected. Could you at least as a note about this in the changelog file?

I'd still prefer if there was some sort of central place containing the changes for all versions, butt that's your call of course.
