### ISSUE TITLE
Wrong DNS API Documentation

### ISSUE THREAD

**Issue by dvdhrm** [hetznercloud/hcloud-python#180]
Hey,

the DNS API docs to query all zones [1] mention a `name` parameter which specifies: `Full name of a zone. Will return an array with one or no results`. Yet, when trying this with a non-existing zone I get an undocumented `404` error rather than an empty array.

Maybe the docs can be updated to say it returns `404`?

Sadly, the DNS APIs are not supported by `hcloud-python` (btw., any particular reason why?) so feel free to refer me to the correct place to report this (or close it, if you feel like it).

Thanks!

[1] https://dns.hetzner.com/api-docs#operation/GetZones

**Comment by apricote** [comment]
Hey @dvdhrm, I have talked to the responsible team internally and they will take a look at this.

**Comment by dvdhrm** [comment]
The documentation is still incorrect.
