### ISSUE TITLE
Rebuild does not return root_password

### ISSUE THREAD

**Issue by pchandra19** [hetznercloud/hcloud-python#181]
## Bug Report

**Current Behavior**
'Rebuild' returns the BoundAction but does not return the "root_password" 

**Input Code**

```
server = self.client.servers.get_by_name(name='server')
res = server.rebuild(Image(id='image_id'))
print(res)
```

**Expected behavior/code**
The 'rebuild' should return  the root_password along with the BoundAction.
The response from the Hetzner API is below ( See possible solution) 

**Environment**
- Python Version: 3.11.2
- Hcloud-Python Version: 1.18.2

**Possible Solution**
```
{
  "action": {
    "command": "rebuild_server",
    "error": {
      "code": "action_failed",
      "message": "Action failed"
    },
    "finished": null,
    "id": 13,
    "progress": 0,
    "resources": [
      {
        "id": 42,
        "type": "server"
      }
    ],
    "started": "2016-01-30T23:50:00+00:00",
    "status": "running"
  },
  "root_password": null
}
```
**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jooola** [comment]
I am not sure if there is a way to fix this without breaking the existing API.
The server `rebuild` method currently [returns a `BoundAction`](https://github.com/hetznercloud/hcloud-python/blob/2ce71e9ded5e9bb87ce96519ce59db942f4f9670/hcloud/servers/client.py#L867), to include the new root password, we will need to wrap the previously returned action in a `RebuildResponse`, including both the `action` and the `root_password`.

**Comment by apricote** [comment]
We had this exact issue in `hcloud-go`: https://github.com/hetznercloud/hcloud-go/pull/245

- We added a new method that returns the proper response
- changed the old method to call the new one and modify the return value to stay consistent
- mark the old method as deprecated
