### ISSUE TITLE
Transfer resources

### ISSUE THREAD

**Issue by Linuxmaster14** [hetznercloud/hcloud-python#190]
## Feature Request

In Hetzner's Public API (https://docs.hetzner.cloud/), there is no transfer of resources (IP, server, etc.) from one project to another.

I saw this in the page requests related to the transfer of resources from Inspect Element, which is used from the following link.

‍`
https://api.hetzner.cloud/v1/_projects/{project_id}/move_resource
`

It would be a good idea to add this to the public API as well.

**Comment by apricote** [comment]
Hey @Linuxmaster14,

I have added your request to our internal feedback tool. As this is currently not part of the public API, hcloud-python can not implement it. To keep the issue tracker cleaned up, I will close this issue now.

**Comment by tumbl3w33d** [comment]
For others hitting this one – it is still not possible to move resources programmatically. You might think you can just ignore that it's an internal API, living on the edge, accepting the risk of a breaking API, however, they won't let you pass with a normal hcloud API token (403). Only if you pass in a bearer token stolen from a browser session you will be able to pass but that defies the purpose of automation.

Dear Hetzner team, it would be great, in case you still don't want to expose that API for whatever reason, if you could at least allow access with a token of some kind for those of us who like automated processes and are ready to take the risk. You could, for example, add a public endpoint `/v1/i-know-what-i-am-doing/auth` so I can retrieve an appropriate token there to do crazy things.

@foertel described the not so exotic use case of distributing a blueprint/golden image across projects in the linked ticket.

**Comment by jooola** [comment]
@tumbl3w33d Thanks for the input, I'll add your vote to our internal feedback tracker.
