### ISSUE TITLE
Howto use wss link to open a console

### ISSUE THREAD

**Issue by tootai** [hetznercloud/hcloud-python#259]
Hi,
I try to open a console link sended per API but don't know what to do with the link (same question as #119)
For example, giving the link
wss://web-console.hetzner.cloud/?server_id=1234567890&token=b0Bzz554oF5T3plFwTjDTTU-hgRT-DaM2neDp2CMHs0

I tried
```
wscat -c wss://web-console.hetzner.cloud/?server_id=1234567890&token=b0Bzz554oF5T3plFwTjDTTU-hgRT-DaM2neDp2CMHs0
```
which ended
```
[2] 294806
                                                                                                                                                              
me@server [~] $ 
[2]  + suspended (tty output)  wscat -c wss://web-console.hetzner.cloud/?server_id=1234567890
```
nothing more. I read that I could use novnc but there I get a red window

```
ERROR SecurityError: The operation is insecure.
https://novnc.com/noVNC/core/websock.js:231:0

open@https://novnc.com/noVNC/core/websock.js:231:21
_connect@https://novnc.com/noVNC/core/rfb.js:551:24
_updateConnectionState@https://novnc.com/noVNC/core/rfb.js:903:22
RFB@https://novnc.com/noVNC/core/rfb.js:279:14
connect@https://novnc.com/noVNC/app/ui.js:1044:18
```
Could someone please show with a clear example how to use the wss link. BTW, running Ubuntu 22.04 and Debian 12.

Thanks for any hint, Daniel

**Comment by jooola** [comment]
Hi Daniel,

Did you quote the URL before running the command? It looks like the first command was put in the background because of the unquoted `&`.
So you wrote: 
```
$ wscat -c wss://web-console.hetzner.cloud/?server_id=1234567890&token=b0Bzz554oF5T3plFwTjDTTU-hgRT-DaM2neDp2CMHs0
```

and your shell understood:

```
$ wscat -c wss://web-console.hetzner.cloud/?server_id=1234567890 &
$ token=b0Bzz554oF5T3plFwTjDTTU-hgRT-DaM2neDp2CMHs0
```

I recommend quoting any URLs you use in the CLI:
```
$ wscat -c "wss://web-console.hetzner.cloud/?server_id=1234567890&token=b0Bzz554oF5T3plFwTjDTTU-hgRT-DaM2neDp2CMHs0"
```

**Comment by tootai** [comment]
Answer was so easy, shame on me, thanks joola \o/

Now I see 
dh@feijoa [~] $ wscat -c "wss://web-console.hetzner.cloud/?server_id=1234567890&token=pnJyQ_SAMvVIyo7S_7EwBf-TY9glDLYRrDEa9fvEiIA"
Connected (press CTRL+C to quit)
< RFB 003.008

> 
Disconnected (code: 1003, reason: "only binary, close, ping, and pong frames are supported")
or
Disconnected (code: 1006, reason: "")

The last one seems to be timeout for the valid URL. What are others ?

The output looks like an VNC server, I checked with netstat and saw
tcp        0      0 192.168.10.24:57796     213.239.246.21:443      ESTABLISHED 1001       277012     23147/node

and tried vnc 192:168:10:24::57796 but no luck (TigerVNC). Is this the right way to connect to console ?

Thanks for your help

**Comment by tootai** [comment]
Now I have with xvncviewer
Tue Jul 25 13:43:52 2023
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       unable to connect to socket: Connexion refusée (111)

When I try to connect to xvncviewer 192.168.10.24:38722 (port given by netstat)

**Comment by jooola** [comment]
Hi @tootai,

I don't know if the clients you are using support "VNC over websocket", I haven't tried myself. But this can be the source of the problem you are facing.

I just tried with noVNC https://novnc.com/noVNC/vnc.html, and I was able to edit the remote server configuration in Settings > Advanced. 
![image](https://github.com/hetznercloud/hcloud-python/assets/19195485/3352ca38-3b1b-48e6-908b-b36198acd0af)
(The interface got translated to French sorry).

**Comment by tootai** [comment]
Joola. I already tried novnc but always get error I gave in original message. Attached the copy of the test of today. What I do:
. request a console using api
. get the wss_url: web-console.hetzner.cloud is the server I use in novnc parameter, port 443
. put the server_id=<receided server ID>&token=<received token> in the path
. hit connect button
Result: see attached [screenshot](url) 
![Capture d’écran du 2023-08-07 18-58-28](https://github.com/hetznercloud/hcloud-python/assets/6564304/6a9ae3c0-c5ea-4d0e-b1aa-8b7364cf3b9a)
What's wrong ?

Also, is there a way to use the wss_url without using novnc platform ?

**Comment by jooola** [comment]
I am not able to reproduce your error, you should share more details about the steps you followed.

- Browser name and version
- values you pasted in the configuration fields, 
- Browser console logs.
 
As an example, here are my connection details:
```
Console for server 357214XX:
WebSocket URL: wss://web-console.hetzner.cloud/?server_id=35721422&token=P3I5vK9y3cNqsyiPhXjvbYPMeZcN8BqmA-6NiY8o9JA
VNC Password: AWjHgpXX
```

In noVNC (Settings > Advanced > Websocket) I only changed the following field:
```
Host (Hôte):  web-console.hetzner.cloud
Port [leave it unchanged]: 443
Path (Chemin): /?server_id=35721422&token=P3I5vK9y3cNqsyiPhXjvbYPMeZcN8BqmA-6NiY8o9JA
```
![image](https://github.com/hetznercloud/hcloud-python/assets/19195485/5b7d88d9-4647-46ee-a5bb-694b56be0275)

Then hit "connect", that should ask for a password:
![image](https://github.com/hetznercloud/hcloud-python/assets/19195485/dcfa6715-49a7-4c7b-ad38-4636ae41f5f5)

You should then put the VNC password you got earlier: `VNC Password: AWjHgpXX`

If you have some issues, try again with a new URL. 

I'll keep this issue closed, as it is not related to the python library, but rather on how to use the web socket VNC URL.

**Comment by tootai** [comment]
Got it, I added #<passwd> after the wss url Now it's working.

Thanks a lot jooola for your help.
