### ISSUE TITLE
Use timeouts on API requests

### ISSUE THREAD

**Issue by berkanteber** [hetznercloud/hcloud-python#262]
## Feature Request

**Is your feature request related to a problem? Please describe.**
With [yesterday's incident](https://status.hetzner.com/incident/58232506-2cd2-4ffa-972f-8e14da83bd16) on Cloud API, we've seen that some of our code got stuck. Looking at the logs, these seemed to happen when we use the library. And looking at the repo, it seems that there are no timeouts. So we think, this was why. 

**Describe the solution you'd like**
Customizable (or general but a bit high) timeout value on all requests to API.
 
**Describe alternatives you've considered**
An alternative would be trying to understand if a library is stuck on code, which seems suboptimal.

**Teachability, Documentation, Adoption, Migration Strategy**
As far as I can tell, everything uses `Client._requests_session`, so it could be initialized with timeouts on `Client.__init__()`.

**Comment by jooola** [comment]
Agreed, we should add a timeout option, I'll look into this.
