### ISSUE TITLE
Wrong filters combination in client.servers.get_all

### ISSUE THREAD

**Issue by agusmakmun** [hetznercloud/hcloud-python#333]
## Bug Report

**Current Behavior**

I'm trying to using filter combination using hcloud-python, and found weird things, where the combination is not working as expected. I believe the conditionals should be using `AND` method to filter, not using `OR`.

1. Filter by status running only => no servers.
2. Filter by status running + machine name => found servers.

**Input Code**

```python
In [1]: client.servers.get_all(name="devsecops-box-wgkx6y1e", status=["running"])
Out[1]: [<hcloud.servers.client.BoundServer object at 0x7f73a83c8d60>]

In [2]: client.servers.get_all(status=["running"])
Out[2]: []
```

**Expected behavior/code**

```python
In [1]: client.servers.get_all(name="devsecops-box-wgkx6y1e", status=["running"])
Out[1]: [] <--- should be empty as well.
```

**Environment**

- Python Version: 3.9
- Hcloud-Python Version: 1.32.0

**Possible Solution**

I have checked to the code, and there is no problem with this SDK, probably because of wrong result of `/servers` in BE:

https://github.com/hetznercloud/hcloud-python/blob/main/hcloud/servers/client.py#L514C9-L514C85

```python
response = self._client.request(url="/servers", method="GET", params=params)
```

**Additional context/Screenshots**

| Platform | HCloud Client |
|---------| ------------|
| ![Screenshot 2023-12-05 at 20 09 31](https://github.com/hetznercloud/hcloud-python/assets/7134451/b96050b2-c846-4c5d-bc56-48da040d5e66) | ![Screenshot 2023-12-05 at 20 10 47](https://github.com/hetznercloud/hcloud-python/assets/7134451/7de8ebf7-bb9f-4c87-a0ad-b3d9e5eb242a) |

--------

Alternatively, I'm using this script to handle the above issue:

```python
try:
    # NOTE: have filter combination issue especially for status,
    # please remove below conditionals once it fixed.
    # https://github.com/hetznercloud/hcloud-python/issues/333
    servers: List[BoundServer] = self.client.servers.get_all(**params)
    if only_running:
        servers = [
            server
            for server in servers
            if server.status == HetznerServerStatusChoices.running
        ]
    if use_environment:
        servers = [
            server
            for server in servers
            if server.labels.get("environment") == self.environment
        ]
    return servers
except APIException:
    ...
return []
```

Please let me know once it fixed, so I can update my code.

**Comment by jooola** [comment]
When using the `name` filter in particular, other filters might be ignored. I am investigating and trying to document this behavior for all our endpoints.

**Comment by agusmakmun** [comment]
@jooola sometimes we need filter combination. So, if other filters are ignored it might not a good approach I believe.

**Comment by jooola** [comment]
Changing the behavior of the API would be a breaking change, so I am afraid I will not be able to help you in this regard, but I can maybe give you tips to solve your issue? Have you tried using label selector + status ?
