### ISSUE TITLE
Filter multiple machines with the similar name

### ISSUE THREAD

**Issue by agusmakmun** [hetznercloud/hcloud-python#334]
## Feature Request

For example I have many `devsecops-box` machines such as `devsecops-box-123`, `devsecops-box-456`, etc.

```python
import requests

token = "xxx"
headers = {"Authorization": "Bearer " + token}
url = "https://api.hetzner.cloud/v1/servers"

params = {
    "name": "devsecops-box",
}

r = requests.get(url, headers=headers, params=params)
r.json()["servers"]
```

While trying above code, it's give me **empty result** because the filter by name need to be exactly same.

Based on documentation, there is no way for doing it. Unless we don't use filter.
https://docs.hetzner.cloud/#servers-get-all-servers

**Comment by jooola** [comment]
Hi @agusmakmun 

I understand the need for such feature, but changing this on the API side would be a breaking change. So I am afraid this will not be implemented.

As alternative, I recommend you to use labels to query "groups" of servers. For example, you could set the `group=devsecops-box` label on your servers, and use `params = { "label_selector": "group=devsecops-box" }` to only retrieve the server you need.
