### ISSUE TITLE
v1.33.1 not uploaded to PyPI

### ISSUE THREAD

**Issue by jkreileder** [hetznercloud/hcloud-python#349]
v1.33.1 has not been published to PyPI since you seem to try to login with username and password but PyPI requires two factor authentication now: https://github.com/hetznercloud/hcloud-python/actions/runs/7384447920/job/20087408648#step:7:25

You should use an [API token](https://pypi.org/help/#apitoken) or switch to [trusted publishing](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) with the [pypa/gh-action-pypi-publish action](https://github.com/pypa/gh-action-pypi-publish). The latter requires no credentials at all.

**Comment by jooola** [comment]
Nice catch, I'll fix this immediatly.
