### ISSUE TITLE
wait_until_status_is

### ISSUE THREAD

**Issue by franzs** [hetznercloud/hcloud-python#4]
## Feature Request

[hetznercloud-py](https://github.com/thlisym/hetznercloud-py) has a method `wait_until_status_is` for actions and servers which is very convenient.

Are there any plans to implement something like this in `hcloud-python`?

In general it would be nice to have a way to synchronize actions, e. g.

- create a volume
- wait until it is available
- attach volume to existing server

**Comment by LD250** [comment]
Hi @franzs , thank you for the proposal. I think it makes sense.

I will take it to the next planning session.
