### ISSUE TITLE
libcloud storage support

### ISSUE THREAD

**Issue by gionatamettifogo** [hetznercloud/hcloud-python#47]
Ciao Hetzner,

We use your cloud and storage boxes. We use Apache libcloud to abstract from a specific implementation and found that your storage is not in the library (you can find Amazon, Google, etc).

https://github.com/apache/libcloud

We wrote a driver for libcloud that connects to your storage box via WebDAV. You could add it to Apache libcloud so people could find it and also find you as a cloud provider. I attached the source code below. If you decide to use it I can explain how to add to libcloud, etc and also provide testing code. License is open source.

[webdavdrivers.py.zip](https://github.com/hetznercloud/hcloud-python/files/3306264/webdavdrivers.py.zip)

Cheers

**Comment by LKaemmerling** [comment]
Hello @gionatamettifogo,

thank you for your message and your work on this! The scope of this library is only the Hetzner Cloud API (docs.hetzner.cloud), so we can not support our Storages Boxes, which are parts of our Hetzner Robot (robot.hetzner.com). However, we will have a look on libcloud and will decide if we contribute to this. Thank you!
