### ISSUE TITLE
UserData not available at the server response object

### ISSUE THREAD

**Issue by dspautz** [hetznercloud/hcloud-python#60]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I cannot ask your api for the initial used user_data script

**Describe the solution you'd like**
A user_data attribute on the responded server object would be fine

**Describe alternatives you've considered**
Just save a own database entity for each created server

**Teachability, Documentation, Adoption, Migration Strategy**
```python
response = servers_client.get_by_id(...)
response.server.user_data
```

**Comment by LKaemmerling** [comment]
Actually is it not possible to access the user data through the API.  

I have put it on our Wishes List.
