### ISSUE TITLE
Use looser bounds for future dependency

### ISSUE THREAD

**Issue by decentral1se** [hetznercloud/hcloud-python#68]
## Bug Report

**Current Behavior**

> ERROR: hcloud 1.6.1 has requirement future==0.17.1, but you'll have future 0.18.0 which is incompatible.

With the following requirements file (reproduce with `pip install -r requirements.txt`):

```
ansible==2.8.5
molecule[hetznercloud]==2.22
pip==19.3
setuptools==41.4.0
```

**Expected behavior/code**

Easier bounds so that libraries don't conflict as easily.

**Environment**
- Python 3.7
- Hcloud 1.6.1

**Possible Solution**

Use `<=` and `>=` bounds.

**Comment by LKaemmerling** [comment]
@decentral1se  the release was tagged and will be available within the next minutes (when everything is done here: https://travis-ci.com/hetznercloud/hcloud-python/builds/131987374)

**Comment by decentral1se** [comment]
:rocket:
