### ISSUE TITLE
Cloud-init status

### ISSUE THREAD

**Issue by mikebarkmin** [hetznercloud/hcloud-python#82]
Is there a way to determine, if cloud-init is finished by using this library.

**Comment by Optiligence** [comment]
i use this, although you probably rather want to test if you can actually already connect
or let the instance itself signal that it’s ready
```
for retries in range(10):
    if instance.status == instance.STATUS_RUNNING:
        break
    time.sleep(10)
    instance = instance.update()
assert instance.status == instance.STATUS_RUNNING
```

**Comment by LKaemmerling** [comment]
There is no way how we can determine if the server is ready (boot finished), as we don't have access to the server itself. I would recommend looking for `/var/lib/cloud/instance/boot-finished` on the server.

**Comment by mikebarkmin** [comment]
For future readers: I ended up doing this
```
def exists_remote(host, path):
    """Test if a file exists at path on a host accessible with SSH."""
    status = subprocess.call(["ssh", host, "test -f {}".format(pipes.quote(path))])
    if status == 0:
        return True
    if status == 1:
        return False
    raise Exception("SSH failed")

while not exists_remote(f"root@{ip}", "/var/lib/cloud/instance/boot-finished"):
    print(".")
    time.sleep(5)

```

**Comment by rvencu** [comment]
Hi @mikebarkmin can you provide an example of how do you get the ip of the server after creating it? It seems you already done that and I cannot find this info on the docs...

**Comment by mikebarkmin** [comment]
Hi. You can get the IP when you create a new server:

```
def up(server_type="cx11"):
    client = Client(token=os.getenv("HCLOUD_API_TOKEN"))

    with open("cloud-config.yml", "r") as user_data:
        response: CreateServerResponse = client.servers.create(
            name="load-testing",
            server_type=ServerType(name=server_type),
            image=Image(name="ubuntu-20.04"),
            ssh_keys=client.ssh_keys.get_all(),
            user_data=user_data.read()
        )
        server: BoundServer = response.server
        return server.public_net.ipv4.ip
```

I describe it in a tutorial on how to use the hetzner sdk for setting up a load testing environment. https://dev.to/mikebarkmin/spin-up-real-infrastructure-for-load-testing-with-locust-on-hetznercloud-35oa

**Comment by rvencu** [comment]
Thanks a lot, did not find the tutorial before.
