### ISSUE TITLE
hcloud pip module for Python 3.9

### ISSUE THREAD

**Issue by dithmer** [hetznercloud/hcloud-python#84]
## Feature Request

Hello,

We are developing a new saltstack cloud driver for the Hetzner Public Cloud using hcloud-python. Saltstacks build chain in github required to have the dependencies available in `pip` for Python 3.9, but there is no `hcloud` available via `pip install hcloud==1.6.3` for Python 3.9. Would it be possible to make this available?

Link to saltstack/salt - PR: https://github.com/saltstack/salt/pull/57453
Link to saltstack/salt - specific check: https://jenkinsci.saltstack.com/job/pr-pre-commit/job/PR-57453/7/console

Best regards

**Comment by LKaemmerling** [comment]
Hey @dithmer,

we have released v1.7.0 which supports Python 3.9.
